let messages = ["Send someone a handwritten letter or postcard",
"Bring someone a souvenir",
"Cook someone a meal",
"Bake someone treats",
"Put your phone away (especially if you’re on it a lot)",
"Do someone’s laundry",
"Make someone a playlist",
"Give someone a book you think they’d like",
"Give someone a hug",
"Write a list of things you love about someone",
"Wash someone’s car",
"Babysit, dogsit, or catsit for free",
"Go out of the way to offer someone a ride",
"Mow someone’s lawn after mowing your own",
"Send someone a care package",
"Take someone to the movie",
"Take someone on a spontaneous adventure",
"Throw someone a surprise party",
"Bring doughnuts or desserts to work",
"Leave a positive sticky note on someone’s desk",
"Take someone out to lunch",
"Lend out your umbrella when it’s pouring outside",
"Make two lunches for work and give one away",
"Take someone to a mani, pedi, or massage",
"Teach someone a recipe",
"Leave quarters at the laundromat",
"Pay the toll for the person behind you",
"Give someone a compliment",
"Leave a larger than normal tip",
"Buy someone behind you in line their morning coffee",
"Pay for someone’s groceries behind you",
"Give up a good parking spot",
"Send a box of our fave donuts, bagels, or muffins to a construction site",
"Smile at someone… just because (even Mother Teresa said, “We shall never know all the good that a simple smile can do.”)",
"Hold the elevator or door open",
"Put change in someone’s expired parking meter (keep in mind that re-metering is illegal in some cities, especially when you are allowing them to stay beyond the time limit)",
"Let someone behind you at the supermarket check out first",
"Send dessert to another table",
"Give up your seat on the bus or subway",
"Give up your window or aisle seat for someone who has a middle seat",
"Bring your flight attendant some chocolates",
"Help someone struggling with heavy bags",
"Give someone a flower or bouquet / Bring flowers to a nursing home",
"Help someone take a photo",
"Take time to give someone who looks lost directions",
"Stop and help someone with a flat tire",
"Carry a $5 gift card with you and give it someone randomly",
"Help someone load their luggage into the overhead bin",
"Give someone else the cab that you hailed",
"Let someone else get seated before you at a busy restaurant",
"Share your table with someone at a busy food court"
];



const but = document.getElementById("demo");

function message () {
    return but.innerHTML = messages[Math.floor(Math.random() * messages.length)] + ".";
}